### PR TITLE
Chore: update devphase

### PR DESCRIPTION
**Pull request by FaisalAl-Tameemi**
What changed?

* Remove `devphase` package in favor of `@devphase/cli` and `@devphase/service`
* Update `devphase.config.ts` to latest + increase timeout (not necessary for all systems)

How to test?

1. In a terminal window, run `npx @devphase/cli stack run`
2. In another terminal window, run `npx @devphase/cli stack setup`
3. Use Phat Contracts UI to connect (tested by running the UI repo locally)

Other notes:
* The tests currently still fail (ex: `substrate.test.ts`), will try fixing those soon

---

Edit: added some more changes below to resolve test issues

### CODE REVIEW

**Comment by h4x3rotab** [comment]
Thank you. Looks good to me.

**Comment by FaisalAl-Tameemi** [comment]
What changed?

* Generate new typings
* Refactor `substrate.test.ts`

How to test?

* Run `npx @devphase/cli contract test` from the `/phat` directory

**Comment by FaisalAl-Tameemi** [comment]
@h4x3rotab Changed this from draft to open.

**Review by h4x3rotab — APPROVED** [review]
LGTM

**Comment by h4x3rotab** [comment]
Thanks for the contribution! Consider to request a tip here: https://phala.subsquare.io/treasury/tips

**Pull request merged**
