### PR TITLE
Adapt rollup queue implementation

### PR DESCRIPTION
**Pull request by kvinwang**
This PR adapts the rollup queue implementation to the recent design in https://github.com/Phala-Network/phala-blockchain/pull/1075.

### CODE REVIEW

**Comment by kvinwang** [comment]
The API seems isn't compatible. Let me mark it as a draft and think twice.

**Comment by h4x3rotab** [comment]
Let's merge the QueueSession to the normal Session. It can be probably implemented as a trait so that ppl can explicitly use the trait when they want the queue

**Comment by h4x3rotab** [comment]
Ideally, we may have some API on the client side like this:

```rust

fn poll(&self) -> Result {
  RollupClient::new(self.client_config)
    .handle_messages(self)
    .use(|client| {
      let value: u32 = client.session.get(b"a-counter")?;
      client.session.put(value + 1)?;
      client.action(Actions::Reply(...));
    })
    .commit()
}

impl MessageHandler for MyContract {
  fn on_message(&self, client: &mut Client, msg: &[u8], idx: u32) -> Result<()> {
    // check remaining gas or execution time?
    // handle `msg`
  }
}


```

**Comment by kvinwang** [comment]
Closed in favor of https://github.com/Phala-Network/phala-blockchain/pull/1084

**Pull request closed without merging**
